sudo: required
language: generic
services:
  - docker

before-install:
  - docker build -t tsvety/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tsvety/react-test npm run test

after_success:
   - docker build -t tsvetygoranova/multi-client ./client
   - docker build -t tsvetygoranova/multi-nginx ./nginx
   - docker build -t tsvetygoranova/multi-server ./server
   - docker build -t tsvetygoranova/multi-worker ./worker

   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   
   - docker push tsvetygoranova/multi-client
   - docker push tsvetygoranova/multi-nginx
   - docker push tsvetygoranova/multi-server
   - docker push tsvetygoranova/multi-worker
   